apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mk-addrlist-generator.fullname" . }}-config
  labels:
    {{- include "mk-addrlist-generator.labels" . | nindent 4 }}
data:
  config.yaml: |
    config:
      {{- if .Values.config.timeout }}
      timeout: {{ .Values.config.timeout | quote }}
      {{- end }}
      {{- if .Values.config.commentPrefix }}
      commentPrefix: {{ .Values.config.commentPrefix | quote }}
      {{- end }}
    {{- if .Values.config.lists }}
    lists:
      {{- toYaml .Values.config.lists | nindent 6 }}
    {{- end }}
