apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mk-addrlist-generator.fullname" . }}-config
  labels:
    {{- include "mk-addrlist-generator.labels" . | nindent 4 }}
data:
  config.yaml: |
    output_format: {{ .Values.config.outputFormat }}
    log_level: {{ .Values.config.logLevel }}
    server:
      port: {{ .Values.config.server.port }}
      metrics_enabled: {{ .Values.config.server.metricsEnabled }}
    {{- if .Values.config.lists }}
    lists:
      {{- toYaml .Values.config.lists | nindent 6 }}
    {{- end }}
